### ISSUE TITLE
CI gets run for foreign pull requests, but fails because of missing Secrets

### ISSUE THREAD

**Issue by cfra** [Rote-Beete/juntagrico-docker#11]
When pull requests are opened from a fork, CI is run without secrets for security reasons.

This makes the CI fail because we include tasks like the Docker image push that require these credentials.

We should probably either:

a) Don't run CI for foreign pull requests
b) Guard CI steps that require secrets so they are skipped when Secrets are unavailable

**Comment by cfra** [comment]
It seems I did not review #14 closely enough.

There is a conflict with step IDs that I only realized after merging it, when updating #8.

I took the liberty to stray from best practice and perform the fix in #8 to verify actions will be performed correctly for the case of a foreign PR.

**Comment by n3ph** [comment]
I do not remember why I was using `id` at all. AFAIK we can also get rid of it. 
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsid
